---
swagger: "2.0"
info:
  description: "BeaconFUNプロジェクト「Youbeacomm」のAPIサーバです"
  version: "1.0.0"
  title: "Youbeacomm API"
host: "virtserver.swaggerhub.com"
basePath: "/shield-9/Youbeacomm/1.0.0"
tags:
- name: "device"
  description: "ユーザの端末"
- name: "beacon"
  description: "ビーコンの検知"
- name: "phrase"
  description: "フレーズ候補の提案"
schemes:
- "https"
paths:
  /device:
    post:
      tags:
      - "device"
      summary: "新しい端末IDを割り当てる"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "新しくシステムに登録する端末の情報"
        required: true
        schema:
          $ref: "#/definitions/DeviceMeta"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/DeviceId"
        400:
          description: "Bad request. Invalid Parameters."
  /beacon/passed:
    post:
      tags:
      - "beacon"
      summary: "ビーコン検知の通知"
      description: ""
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "検知したビーコンの情報"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request. Invalid Parameters."
  /phrase/suggestions/location/{deviceId}/:
    get:
      tags:
      - "phrase"
      summary: "位置情報ベースのフレーズ候補の取得"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "deviceId"
        in: "path"
        description: "端末のID"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrases"
  /phrase/suggestions/frequent/:
    get:
      tags:
      - "phrase"
      summary: "頻出フレーズ候補の取得"
      description: ""
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrases"
definitions:
  Beacon:
    type: "object"
    required:
    - "accuracy"
    - "major"
    - "minor"
    - "proximityUUID"
    properties:
      proximityUUID:
        type: "string"
        format: "uuid"
        example: "b72fd7cb-3e38-442c-b437-79a0c8ad33c2"
      major:
        type: "number"
      minor:
        type: "number"
      accuracy:
        type: "number"
        format: "double"
        example: 10.3
  DeviceId:
    type: "string"
    format: "uuid"
    description: "端末ID\n\nシステムが自動的に割り当てる端末毎の固有値"
    example: "7967cad0-317d-4a97-af00-77cd3b964632"
  DeviceMeta:
    type: "object"
    required:
    - "os_lang"
    - "os_name"
    - "os_version"
    properties:
      os_name:
        type: "string"
        example: "iOS"
        description: "OSの名前\n\niOSの場合: UIDevice.systemName()の値"
      os_version:
        type: "string"
        example: "8.1"
        description: "OSのバージョン\n\niOSの場合: UIDevice.systemVersion()の値"
      os_lang:
        type: "string"
        format: "iso639-1"
        example: "en"
        description: "OSの言語\n\nISO 639-1で規定されている言語コードの値"
  Phrases:
    type: "array"
    items:
      $ref: "#/definitions/Phrase"
    example:
    - id: "96ce2a83-a3a6-445a-98ea-50590a1675c8"
      strings:
      - lang: "en"
        string: "Could you take a photo?"
      - lang: "ja"
        string: "写真を撮ってもらえますか？"
    - id: "64518d78-85e4-49c7-9670-3fe6a1a31f1d"
      strings:
      - lang: "en"
        string: "How can I get to Hakodate station?"
      - lang: "ja"
        string: "函館駅にはどうすれば行けますか？"
  Phrase:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "フレーズのID\nこのIDは1つ以上の言語で文字列に表現されたフレーズを識別する。"
      strings:
        type: "array"
        description: "フレーズの文字列\n1つ以上の言語での表現が利用可能であることと、1つの言語での表現は1つであることのみが保証される。"
        items:
          $ref: "#/definitions/L10nString"
    example:
      id: "5c9b5f28-1cfb-4e3a-b77e-6cf8d2a35b68"
      strings:
      - lang: "en"
        string: "Could you take a photo?"
      - lang: "ja"
        string: "写真を撮ってもらえますか？"
  L10nString:
    type: "object"
    properties:
      lang:
        type: "string"
        format: "iso639-1"
        example: "en"
      string:
        type: "string"
        example: "Could you take a photo?"
  body:
    type: "object"
    properties:
      device:
        $ref: "#/definitions/DeviceId"
      beacon:
        $ref: "#/definitions/Beacon"
