---
swagger: "2.0"
info:
  description: "BeaconFUNプロジェクト「Youbeacomm」のAPIサーバです\n\n利用可能なAPIのバージョンを確認するため、端末は他\
    のAPIにアクセスする前に、`/`にアクセスする必要があります。また、新しい端末は`/device/`にアクセスして、端末IDの割り当てを受けることで、端末\
    の利用者に対してパーソナライズされたコンテンツを利用することができるようになります。\n\n# 実装上の注意\nこのAPIを利用するすべてのクライアントアプ\
    リケーションは、以下のことを前提に実装する必要があります。\n* Base URLが将来的に変更されること\n* エンドポイントが追加・廃止・分割・統合・変\
    更されること\n* ただし、`/`は将来にわたって`available_api_versions`要素が含まれること"
  version: "1.0.0-alpha"
  title: "Youbeacomm API"
host: "virtserver.swaggerhub.com"
basePath: "/shield-9/Youbeacomm/1.0.0-alpha"
tags:
- name: "meta"
  description: "APIのメタデータ"
- name: "device"
  description: "ユーザの端末"
- name: "beacon"
  description: "ビーコンの検知"
- name: "phrase"
  description: "フレーズ候補の提案"
schemes:
- "https"
paths:
  /:
    get:
      tags:
      - "meta"
      summary: "APIのメタデータを取得する"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/APIMeta"
  /device/:
    post:
      tags:
      - "device"
      summary: "新しい端末IDを割り当てる"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "新しくシステムに登録する端末の情報"
        required: true
        schema:
          $ref: "#/definitions/DeviceMeta"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/DeviceId"
        400:
          description: "Bad request. Invalid Parameters."
  /beacon/passed/:
    post:
      tags:
      - "beacon"
      summary: "ビーコン検知を通知する"
      description: ""
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "BeaconPassed"
        description: "検知したビーコンの情報"
        required: true
        schema:
          $ref: "#/definitions/BeaconPassed"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request. Invalid Parameters."
  /phrase/{phraseId}/:
    get:
      tags:
      - "phrase"
      summary: "フレーズの情報を取得する"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "phraseId"
        in: "path"
        description: "フレーズのID"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrase"
        404:
          description: "No such phrase found."
  /phrase/{phraseId}/responses/:
    get:
      tags:
      - "phrase"
      summary: "応答のフレーズ候補を取得する"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "phraseId"
        in: "path"
        description: "フレーズのID"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrases"
        404:
          description: "No such phrase found."
  /phrase/suggestions/location/{deviceId}/:
    get:
      tags:
      - "phrase"
      summary: "位置情報ベースのフレーズ候補を取得する"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "deviceId"
        in: "path"
        description: "端末のID"
        required: true
        type: "string"
        format: "uuid"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrases"
  /phrase/suggestions/frequent/:
    get:
      tags:
      - "phrase"
      summary: "頻出のフレーズ候補を取得する"
      description: ""
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Phrases"
definitions:
  APIMeta:
    type: "object"
    required:
    - "available_api_versions"
    properties:
      available_api_versions:
        type: "array"
        example:
        - "1.0.0-alpha"
        - "1.0.0-alpha.2017092905"
        - "1.0.0-alpha.2017103001"
        items:
          type: "string"
          format: "semver"
  Beacon:
    type: "object"
    required:
    - "accuracy"
    - "major"
    - "minor"
    - "proximityUUID"
    properties:
      proximityUUID:
        type: "string"
        format: "uuid"
        example: "b72fd7cb-3e38-442c-b437-79a0c8ad33c2"
      major:
        type: "number"
      minor:
        type: "number"
      accuracy:
        type: "number"
        format: "double"
        example: 10.3
  DeviceId:
    type: "string"
    format: "uuid"
    description: "端末ID\n\nシステムが自動的に割り当てる端末毎の固有値"
    example: "7967cad0-317d-4a97-af00-77cd3b964632"
  DeviceMeta:
    type: "object"
    required:
    - "os_lang"
    - "os_name"
    - "os_version"
    properties:
      os_name:
        type: "string"
        example: "iOS"
        description: "OSの名前\n\niOSの場合: UIDevice.systemName()の値"
      os_version:
        type: "string"
        example: "8.1"
        description: "OSのバージョン\n\niOSの場合: UIDevice.systemVersion()の値"
      os_lang:
        type: "string"
        format: "iso639-1"
        example: "en"
        description: "OSの言語\n\nISO 639-1で規定されている言語コードの値"
  Phrases:
    type: "array"
    items:
      $ref: "#/definitions/Phrase"
    example:
    - id: "96ce2a83-a3a6-445a-98ea-50590a1675c8"
      strings:
      - lang: "en"
        string: "Could you take a photo?"
      - lang: "ja"
        string: "写真を撮ってもらえますか？"
    - id: "64518d78-85e4-49c7-9670-3fe6a1a31f1d"
      strings:
      - lang: "en"
        string: "How can I get to Hakodate station?"
      - lang: "ja"
        string: "函館駅にはどうすれば行けますか？"
  Phrase:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "フレーズのID\nこのIDは1つ以上の言語で文字列に表現されたフレーズを識別する。"
      strings:
        type: "array"
        description: "フレーズの文字列\n1つ以上の言語での表現が利用可能であることと、1つの言語での表現は1つであることのみが保証される。"
        items:
          $ref: "#/definitions/L10nString"
    example:
      id: "5c9b5f28-1cfb-4e3a-b77e-6cf8d2a35b68"
      strings:
      - lang: "en"
        string: "Could you take a photo?"
      - lang: "ja"
        string: "写真を撮ってもらえますか？"
  L10nString:
    type: "object"
    properties:
      lang:
        type: "string"
        format: "iso639-1"
        example: "en"
      string:
        type: "string"
        example: "Could you take a photo?"
  BeaconPassed:
    type: "object"
    properties:
      device:
        $ref: "#/definitions/DeviceId"
      beacon:
        $ref: "#/definitions/Beacon"
